---
- name: remove irules 
  hosts: "{{ hosts }}"
  connection: local

  tasks:
    - name: Remove the iRule irule-sorry.tcl 
      bigip_irule:
        module: "ltm"
        server: "{{ inventory_hostname }}"
        user: "{{ username }}"
        password: "{{ password }}"
        name: "Sorry_iRule"
        src: "irules/irule-sorry.tcl"
        state: "absent"
        validate_certs: "no"

    - name: Remove the iRule bodgeit-rewrite.tcl
      bigip_irule:
        module: "ltm"
        server: "{{ inventory_hostname }}"
        user: "{{ username }}"
        password: "{{ password }}"
        name: "Bodgeit_Rewrite"
        src: "irules/bodgeit-rewrite.tcl"
        state: "absent"
        validate_certs: "no"
...
